### ISSUE TITLE
Can't compile octotiger with gcc+datapar enabled

### ISSUE THREAD

**Issue by DavidPfander-UniStuttgart** [STEllAR-GROUP/octotiger#23]
@hkaiser:
Compiling octotiger with datapar (Vc-variant) doesn't compile with gcc 6.2.
With the Vc-types enabed, in https://github.com/STEllAR-GROUP/octotiger/blob/master/src/grid_output.cpp#L282:

				cnt += foo(&(G[iii][0]), sizeof(real), NGF, fp) * sizeof(real);

GCC complains that I take the address of a temporary, because the bracket operator on a Vc-type returns the underlying type (aka double in this case). However, the bracket operator of the original class returns "double &".

The error is therefore due to https://github.com/STEllAR-GROUP/octotiger/blob/master/src/simd.hpp#L403.

There are further errors. Certain construct with a preceding "#pragma GCC ivdep" don't seem to compile with my gcc (6.2).

**Comment by hkaiser** [comment]
This should be fixed similarly to: https://github.com/STEllAR-GROUP/octotiger/blob/master/src/grid_output.cpp#L316

**Comment by DavidPfander-UniStuttgart** [comment]
The fix doesn't fix the problem.
 
In contrast to L316, stuff gets written to the vector variable, so we cannot store it in a local variable that is then thrown away. We need the underlying vector type to return a 'double &'.

**Comment by DavidPfander-UniStuttgart** [comment]
Has been resolved via some other issue.
